In [1]:
import numpy as np

## numpy array(numpy dizi)

In [2]:
benimListem=[20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
type(np.array(benimListem))

numpy.ndarray

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
type(matrixListesi)

list

In [8]:
matrixListesi[1]

[20, 30, 40]

In [9]:
matrixListesi[1][0]

20

In [10]:
np.array(matrixListesi) # diziye cevirdik

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
list(range(14))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [13]:
np.arange(0,10) # sonuc olarak numpy dizisi çıkarır

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)  # 1 den 10 a kadar ki çft sayılar,10 stop değeri bu yüzden 10 u almıyoruz

array([0, 2, 4, 6, 8])

## zeros

In [15]:
np.zeros(5) # içeride 5 tane 0 olan dizi üretir

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,2))  # çift parantez kullanarak yazılır matris çıkartmak gerekirse

array([[0., 0.],
       [0., 0.]])

In [17]:
np.ones(5) # 5 elemnlı dizi hepsi 1

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [19]:
np.linspace(0,20,5)  # 0 ile 20 arasında 5 elemanlı dizi oluştur, aralarındakil boşluk eşit olacak şekilde

array([ 0.,  5., 10., 15., 20.])

In [20]:
np.linspace(0,171,13) # 0 dan 171 e kadar git eşit aralıklı 13 sayı olan dizi oluştur

array([  0.  ,  14.25,  28.5 ,  42.75,  57.  ,  71.25,  85.5 ,  99.75,
       114.  , 128.25, 142.5 , 156.75, 171.  ])

## eye

In [21]:
np.eye(3) # birim matris oluşturur 3*3 boyutlu

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(9) #9*9 boyutlu birim matris oluşturur

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [23]:
np.random.randn(4) # random dizi döndürür, tek boyutludur

array([-0.24137179, -0.56864518, -2.45565502,  1.70532738])

In [24]:
np.random.randn(4,4) # 4*4 boyutund ratgele bir matri dizisi oluşturur

array([[-0.00771836,  0.40000043, -0.02238885, -1.13367297],
       [-0.2551097 ,  0.15802573, -2.04434799, -0.1757593 ],
       [-1.06765268, -2.01281897,  1.18170605,  1.78104991],
       [ 0.41197736,  0.88655316, -1.08772632, -0.23219307]])

In [25]:
np.random.randint(1,10) # 1 -10 araı bir değer döndür 1 dhil 10 dahil değil

4

In [26]:
np.random.randint(1,10,5) # 1-10 arası 5 sayı döndür

array([9, 3, 4, 1, 6])

In [27]:
benimNumpyDizim = np.arange(30) # 1 den 30 a kadar olan sayıları numpy dizii olarak değişkene ata

In [28]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
benimRandomDizim= np.random.randint(3,400,4) # 3-400 arası rastgele 4 int değer döndür

In [30]:
benimRandomDizim

array([321, 230, 207, 314])

In [31]:
benimRandomDizim2= np.random.randn(3,2) # 3*2 boyutunda rastgele matris döndür

In [32]:
benimRandomDizim2

array([[ 0.64187989, -0.59526331],
       [-0.97793899,  0.92371422],
       [ 1.2175023 ,  0.11116709]])

## numpy dizi methodları

In [33]:
benimNumpyDizim.reshape(5,6) # reshabe: yeniden şekillendir ** 30 rakam olduğu için 5*6 boyutu olmalı yoka hata verir

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
type(benimNumpyDizim.reshape(5,6))

numpy.ndarray

In [35]:
benimNumpyDizim.max()

29

In [36]:
benimNumpyDizim.mean() # ort

14.5

In [37]:
benimRandomDizim.min() 

207

In [38]:
benimRandomDizim.argmax() # maximumu kacıncı indis

0

In [39]:
benimRandomDizim.argmin() # min in indisi

2

In [40]:
benimRandomDizim.shape  # şekil, şeklini görmek için kullanılır

(4,)

In [41]:
reshapeDizim=benimNumpyDizim.reshape(5,6)

In [42]:
reshapeDizim.shape

(5, 6)

## Numpy Operasyonlar

In [43]:
import numpy as np 

In [44]:
benimDizim =np.arange(0,15) # 0 dan 15 e kadar 

In [45]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
benimDizim[5] # benimDizimin 5. indisi, indisler 0 dan başlıyor

5

In [47]:
benimDizim[3:15] # 3 ile 15 arasını getir

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
benimDizim[3:10]=-5  # benimDizimde 3:10 arasını -5 yap

In [49]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5, -5, -5, 10, 11, 12, 13, 14])

In [50]:
baskaDizi=np.arange(0,24)

In [51]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
slicingDizisi=baskaDizi[4:9]

In [53]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [54]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
slicingDizisi= 700 # diziye int olan 700 ü atadık ve özelliğini kaybetti

In [56]:
slicingDizisi

700

In [57]:
slicingDizisi=baskaDizi[4:9]

In [58]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [59]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
slicingDizisi[:] =700 # içerideki tüm rakamları 700 yaptı

In [61]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [62]:
baskaDizi  # slising ile alınan rakamlar buradada değişti

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [63]:
ornekDizi=np.arange(0,24)

In [64]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [65]:
ornekDiziKopya=ornekDizi.copy() # slicing işlemi yaparken ana dizideki değerler değiştiği için kopyasını ürettik

In [66]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
ornekDiziKopyaSlicing=ornekDiziKopya[3:6]

In [68]:
ornekDiziKopyaSlicing[:]=800

In [69]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [70]:
ornekDiziKopya

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

# slicing ve kopya değişkenlerinde işlem gören diziler de değişiklikler var fakat örnekDizi arrayini sadece kopyalamak için kullandık, bu nedenle bu dizi aynı şekilde sonuç verdi

In [71]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix 

In [72]:
benimListem=[[10,20,30],[20,30,40],[40,50,60]]

In [73]:
benimMatrixDizim=np.array(benimListem)

In [74]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [75]:
benimMatrixDizim[0]  # 0. satır

array([10, 20, 30])

In [76]:
benimMatrixDizim[1] [2] # 1. satır 2. sütun 0 dan basşlar indexler

40

In [77]:
benimMatrixDizim[1,2] # yukarıdaki gibi çalışır

40

In [78]:
benimMatrixDizim[1:,2]

array([40, 60])

In [79]:
benimMatrixDizim[2:,0]

array([40])

In [80]:
yeniListe=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14], [15,16,17,18,19],[20,21,22,23,24]]

In [81]:
yeniMatrix=np.array(yeniListe)

In [82]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [83]:
yeniMatrix[2:,3]

array([13, 18, 23])

In [84]:
yeniMatrix[[0,2,4]] # 0 2 ve 4. indexleri verdi

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operasyonlar

In [85]:
yeniBirDizi=np.random.randint(1,100,20) # 1-100 arası 20 rakam

In [86]:
yeniBirDizi

array([21, 63, 62, 94, 80, 36, 66,  9, 20, 28, 86, 79, 12, 25, 65, 16, 35,
       71, 94, 90])

In [87]:
yeniBirDizi>24 # 24 ten büyükler

array([False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True])

In [88]:
yeniBirDizi

array([21, 63, 62, 94, 80, 36, 66,  9, 20, 28, 86, 79, 12, 25, 65, 16, 35,
       71, 94, 90])

In [89]:
sonucDizisi=yeniBirDizi>24

In [90]:
sonucDizisi

array([False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True])

In [91]:
yeniBirDizi

array([21, 63, 62, 94, 80, 36, 66,  9, 20, 28, 86, 79, 12, 25, 65, 16, 35,
       71, 94, 90])

In [92]:
yeniBirDizi[sonucDizisi] # sadece 24 ten büyükleri filtreledi

array([63, 62, 94, 80, 36, 66, 28, 86, 79, 25, 65, 35, 71, 94, 90])

In [93]:
yeniBirDizi

array([21, 63, 62, 94, 80, 36, 66,  9, 20, 28, 86, 79, 12, 25, 65, 16, 35,
       71, 94, 90])

In [94]:
yeniBirDizi[yeniBirDizi>24]

array([63, 62, 94, 80, 36, 66, 28, 86, 79, 25, 65, 35, 71, 94, 90])

In [95]:
yirmidört=yeniBirDizi[yeniBirDizi>24]

In [96]:
yirmidört

array([63, 62, 94, 80, 36, 66, 28, 86, 79, 25, 65, 35, 71, 94, 90])

In [97]:
sonDizi=np.arange(0,24)

In [98]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [99]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [100]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [101]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [102]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [103]:
sonDizi/sonDizi  # 0/0 yapamadığı için uyarı verdi

<ipython-input-103-5ae2fd95dfae>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi  # 0/0 yapamadığı için uyarı verdi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [104]:
np.sqrt(sonDizi) # kareköklerini aldık

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [105]:
np.max(sonDizi)

23

In [106]:
np.min(sonDizi)

0

In [107]:
sonDizi.max()

23